/* I have created a small "mock database" which is just an array of objects containing all of the user data for the challenge. I chose to structure the page content this way to better emulate how something like this would function in a production environment. */

export const mockDatabase = [
  {
    user: "Mark Webber",
    action: "reacted to your recent post",
    containsURL: "My first tournament today!",
    timing: "1m ago",
    isOnline: true,
    avatarImage: "./assets/images/avatar-mark-webber.webp",
    read: false,
    userMessage: "",
  },
  {
    user: "Angela Gray",
    action: "followed you",
    containsURL: "",
    timing: "5m ago",
    isOnline: true,
    avatarImage: "./assets/images/avatar-angela-gray.webp",
    read: false,
    userMessage: "",
  },
  {
    user: "Jacob Thompson",
    action: "has joined your group",
    containsURL: "Chess Club",
    timing: "1 day ago",
    isOnline: true,
    avatarImage: "./assets/images/avatar-jacob-thompson.webp",
    read: false,
    userMessage: "",
  },
  {
    user: "Rizky Hasanuddin",
    action: "sent you a private message",
    containsURL: "",
    timing: "5 days ago",
    isOnline: false,
    avatarImage: "./assets/images/avatar-rizky-hasanuddin.webp",
    read: true,
    userMessage:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
  },
  {
    user: "Kimberly Smith",
    action: "commented on your picture",
    containsURL: "",
    timing: "1 week ago",
    isOnline: false,
    avatarImage: "./assets/images/avatar-kimberly-smith.webp",
    read: true,
    userMessage: "./assets/images/image-chess.webp",
  },
  {
    user: "Nathan Peterson",
    action: "reacted to your recent post ",
    containsURL: "5 end-game strategies to increase your win rate",
    timing: "2 weeks ago",
    isOnline: false,
    avatarImage: "./assets/images/avatar-nathan-peterson.webp",
    read: true,
    userMessage: "",
  },
  {
    user: "Anna Kim",
    action: "left the group Chess Club",
    containsURL: "Chess Club",
    timing: "2 weeks ago",
    isOnline: false,
    avatarImage: "./assets/images/avatar-anna-kim.webp",
    read: true,
    userMessage: "",
  },
];
